Update CodeQL workflow

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -6,63 +6,41 @@ on:
     branches: [ main ]
   pull_request:
     branches: [ main ]
+# Cancel in-progress job or run for the current workflow
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   analyze:
     name: Analyze
     runs-on: ubuntu-latest
     permissions:
+      # Required for all workflows
+      security-events: write
+
+      # Only required for workflows in private repositories
       actions: read
       contents: read
-      security-events: write
-    env:
-      CMSIS_PACK_ROOT: /tmp/.packs-${{ github.run_id }}
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
-
-    - name: Install build dependencies
-      run: |
-        sudo apt install gcc-arm-none-eabi ninja-build cmake
-
-    - name: Cache pack folder
-      id: cache-packs
+    - name: Cache Arm Compiler 6
       uses: actions/cache@v3
       with:
-        key: packs-${{ github.run_id }}
-        restore-keys: |
-          packs-
-        path: /tmp/.packs-${{ github.run_id }}
+        key: armcompiler-6.20.0
+        path: /home/runner/standalone-linux-x86_64-rel.tgz
 
-    - name: Install CMSIS-Toolbox
+    - name: Install Arm Compiler 6.20.0
+      working-directory: /home/runner
       run: |
-        wget https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/download/1.3.0/cmsis-toolbox.sh
-        chmod +x cmsis-toolbox.sh
-        sudo ./cmsis-toolbox.sh <<EOI
-        /opt/ctools
-        $CMSIS_PACK_ROOT
+        test -f standalone-linux-x86_64-rel.tgz || \
+          wget https://artifacts.keil.arm.com/arm-compiler/6.20/21/standalone-linux-x86_64-rel.tgz
+        mkdir -p arm-compiler-6.20.0
+        tar xf standalone-linux-x86_64-rel.tgz -C arm-compiler-6.20.0
+        echo "AC6_TOOLCHAIN_6_20_0=$(pwd)/arm-compiler-6.20.0/bin" >> $GITHUB_ENV
 
-
-        $(dirname $(which arm-none-eabi-gcc 2>/dev/null))
-
-        EOI
-        echo "/opt/ctools/bin" >> $GITHUB_PATH
-        echo "cpackget : $(which cpackget)"
-        echo "csolution: $(which csolution)"
-        echo "cbuild   : $(which cbuild)"
-
-    - name: Initialize packs folder
-      if: steps.cache-packs.outputs.cache-hit != 'true'
-      run: cpackget init https://www.keil.com/pack/index.pidx
-
-    - name: Update pack index
-      if: steps.cache-packs.outputs.cache-hit == 'true'
-      run: cpackget update-index
-
-    - name: Install build.py requirements
-      run: pip install -r requirements.txt
-      working-directory: Project
+    - name: Checkout repository
+      uses: actions/checkout@v3
 
     # Initializes the CodeQL tools for scanning.
     - name: Initialize CodeQL
@@ -71,11 +49,33 @@ jobs:
         languages: cpp
         queries: security-and-quality
 
-    - name: Build projects
+    - uses: ammaraskar/gcc-problem-matcher@master
+
+    - name: Setup environment and build projects
       working-directory: Project
       run: |
+        echo "Install Python requirements"
+        pip install -r requirements.txt
+
+        echo "Activate vcpkg environment"
+        . <(curl https://aka.ms/vcpkg-init.sh -L)
+        vcpkg activate --project vcpkg-cfg-codeql.json
+
+        echo "Activate Arm tool license"
+        ${AC6_TOOLCHAIN_6_20_0}/armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0
+
+        echo "Check tool environment"
+        echo "AC6       : $(which $AC6_TOOLCHAIN_6_20_0/armclang)"
+        echo "GCC       : $(which arm-none-eabi-gcc)"
+        echo "cbuild    : $(which cbuild)"
+        echo "cpackget  : $(which cpackget)"
+        echo "csolution : $(which csolution)"
+
+        echo "Download and install CMSIS packs"
         cpackget add -a -f cpacklist.txt || exit 1
-        python build.py --verbose -c GCC -r RTX5 build || echo "Something failed!"
+
+        echo "Run build script to build test projects"
+        python build.py --verbose build || echo "Something failed!"
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v2
