Update CodeQL workflow

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -7,14 +7,21 @@ on:
   pull_request:
     branches: [ main ]
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   analyze:
     name: Analyze
     runs-on: ubuntu-latest
     permissions:
+      # Required for all workflows
+      security-events: write
+
+      # Only required for workflows in private repositories
       actions: read
       contents: read
-      security-events: write
     env:
       CMSIS_PACK_ROOT: /tmp/.packs-${{ github.run_id }}
 
@@ -22,9 +29,9 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v3
 
-    - name: Install build dependencies
-      run: |
-        sudo apt install gcc-arm-none-eabi ninja-build cmake
+    #- name: Install build dependencies
+    #  run: |
+    #    sudo apt install gcc-arm-none-eabi ninja-build cmake
 
     - name: Cache pack folder
       id: cache-packs
@@ -35,23 +42,6 @@ jobs:
           packs-
         path: /tmp/.packs-${{ github.run_id }}
 
-    - name: Install CMSIS-Toolbox
-      run: |
-        wget https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/download/1.3.0/cmsis-toolbox.sh
-        chmod +x cmsis-toolbox.sh
-        sudo ./cmsis-toolbox.sh <<EOI
-        /opt/ctools
-        $CMSIS_PACK_ROOT
-
-
-        $(dirname $(which arm-none-eabi-gcc 2>/dev/null))
-
-        EOI
-        echo "/opt/ctools/bin" >> $GITHUB_PATH
-        echo "cpackget : $(which cpackget)"
-        echo "csolution: $(which csolution)"
-        echo "cbuild   : $(which cbuild)"
-
     - name: Initialize packs folder
       if: steps.cache-packs.outputs.cache-hit != 'true'
       run: cpackget init https://www.keil.com/pack/index.pidx
@@ -59,6 +49,9 @@ jobs:
     - name: Update pack index
       if: steps.cache-packs.outputs.cache-hit == 'true'
       run: cpackget update-index
+    
+    - name: Download and install CMSIS packs
+      run: cpackget add -a -f cpacklist.txt || exit 1
 
     - name: Install build.py requirements
       run: pip install -r requirements.txt
@@ -74,8 +67,18 @@ jobs:
     - name: Build projects
       working-directory: Project
       run: |
-        cpackget add -a -f cpacklist.txt || exit 1
-        python build.py --verbose -c GCC -r RTX5 build || echo "Something failed!"
+        # echo "Install Python requirements"
+        # pip install -r requirements.txt
+
+        echo "Activate vcpkg environment"
+        . <(curl https://aka.ms/vcpkg-init.sh -L)
+        vcpkg activate
+
+        # Download and install CMSIS packs
+        #cpackget add -a -f cpacklist.txt || exit 1
+
+        # Build test projects
+        python build.py --verbose build || echo "Something failed!"
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v2
